apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: multi-dbench
spec:
  serviceName: "multi-dbench"
  selector:
    matchLabels:
      app: multi-dbench
  replicas: 16
  template:
    metadata:
      labels:
        app: multi-dbench
    spec:
      containers:
      - name: dbench
        image: harbor-repo.vmware.com/vcf-poc-testing/dbench/dbench
        env:
          - name: DBENCH_MOUNTPOINT
            value: /data
        volumeMounts:
          - name: dbench-pv
            mountPath: /data
      volumes:
      - name: dbench-pv
  volumeClaimTemplates:
  - metadata:
      name: dbench-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
